export const sneakers = [
  {
    id: 1,
    brend: "Nike",
    model: "Air Jordan 1",
    image: "JordanBlue",
    price: 14000,
    color: "blue",
  },
  {
    id: 2,
    brend: "Nike",
    model: "Air Jordan 4 KAWS",
    image: "JordanKaws",
    price: 21000,
    color: "black",
  },
  {
    id: 3,
    brend: "Nike",
    model: "Air force 1",
    image: "ForceWhite",
    price: 10000,
    color: "white",
  },
  {
    id: 4,
    brend: "Nike",
    model: "Blazer",
    image: "BlazerGreen",
    price: 11000,
    color: "green",
  },
  {
    id: 5,
    brend: "Nike",
    model: "Air Jordan 1",
    image: "JordanPurple",
    price: 20000,
    color: "purple",
  },
  {
    id: 6,
    brend: "Nike",
    model: "Air Force 1",
    image: "ForcePink",
    price: 13000,
    color: "pink",
  },
  {
    id: 7,
    brend: "Nike",
    model: "Air Jordan 1",
    image: "JordanTieDye",
    price: 22000,
    color: "Tye-Die",
  },
  {
    id: 8,
    brend: "Nike",
    model: "Air Jordan 1",
    image: "JordanZenMaster",
    price: 16000,
    color: "Zen Master",
  },
  {
    id: 9,
    brend: "Nike",
    model: "Air Jordan 4",
    image: "JordanMillitary",
    price: 30000,
    color: "Millitary",
  },
  {
    id: 10,
    brend: "Nike",
    model: "Air Force 1",
    image: "ForceGradient",
    price: 15000,
    color: "gradient",
  },
  {
    id: 11,
    brend: "Nike",
    model: "Blazer",
    image: "BlazerBlue",
    price: 9000,
    color: "blue",
  },
  {
    id: 12,
    brend: "Nike",
    model: "Air Zoom",
    image: "Zoom",
    price: 22000,
    color: "blue",
  },
];
